### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-ansible-role.git`](https://github.com/cisagov/skeleton-ansible-role.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by mcdonnnj** [comment]
@cisagov/team-ois I would like to merge this with these tests failing. I created [cisagov/ansible-role-xfce-cool/improvement/move_wallpapers_into_repository](https://github.com/cisagov/ansible-role-xfce-cool/tree/improvement/move_wallpapers_into_repository) based on this ~~repository~~ branch with the necessary changes as can be seen in [the diff](https://github.com/cisagov/ansible-role-xfce-cool/compare/lineage/skeleton...improvement/move_wallpapers_into_repository), and it [passes tests fine](https://github.com/cisagov/ansible-role-xfce-cool/actions/runs/1373465648).

Edit: I retract this based on the response from @jsf9k .

**Comment by jsf9k** [comment]
> @cisagov/team-ois I would like to merge this with these tests failing. I created [cisagov/ansible-role-xfce-cool/improvement/move_wallpapers_into_repository](https://github.com/cisagov/ansible-role-xfce-cool/tree/improvement/move_wallpapers_into_repository) based on this repository with the necessary changes as can be seen in [the diff](https://github.com/cisagov/ansible-role-xfce-cool/compare/lineage/skeleton...improvement/move_wallpapers_into_repository), and it [passes tests fine](https://github.com/cisagov/ansible-role-xfce-cool/actions/runs/1373465648).

Why not create a PR to merge `improvement/move_wallpapers_into_repository` into this branch?  That seems cleaner and leaves more of a paper trail than merging something that doesn't pass tests.

**Comment by mcdonnnj** [comment]
> 
> 
> > @cisagov/team-ois I would like to merge this with these tests failing. I created [cisagov/ansible-role-xfce-cool/improvement/move_wallpapers_into_repository](https://github.com/cisagov/ansible-role-xfce-cool/tree/improvement/move_wallpapers_into_repository) based on this repository with the necessary changes as can be seen in [the diff](https://github.com/cisagov/ansible-role-xfce-cool/compare/lineage/skeleton...improvement/move_wallpapers_into_repository), and it [passes tests fine](https://github.com/cisagov/ansible-role-xfce-cool/actions/runs/1373465648).
> 
> Why not create a PR to merge `improvement/move_wallpapers_into_repository` into this branch? That seems cleaner and leaves more of a paper trail than merging something that doesn't pass tests.

That is way smarter. Please see https://github.com/cisagov/ansible-role-xfce-cool/pull/24.

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 👍

**Pull request merged**
